### PR TITLE
Jekyll: Fix many bugs, add new features

### PR DESCRIPTION
**Pull request by markstos**
**UPDATE:** This PR was originally about the narrow scope of fixing the bug below. But I soon ran into a number other bugs and missing features that affected the same parts of the code. It quickly became not feasible to submit separate PRs for them, as many would overlap would conflict, so this PR collects all the fixes I've made. Looking at the individual commits will provide context for each change. 

-----
Bug: "Should import _posts, not "posts""

The Jekyll docs are clear that posts go in "\_posts" (with an
underscore):

https://jekyllrb.com/docs/structure/

While "posts" (no underscore) may be the the name of an output directory
with rendered HTML.

Because HTML is also valid as an impout format, importing "posts" is
no longer supported to avoid confusion.

### CODE REVIEW

**Comment by markstos** [comment]
I've also added a fix to #508 to this PR, as it would have conflicted if I'd submitted it indepdently.

**Comment by markstos** [comment]
I implemented support for HTML format content (#507) on this branch, since it was also going to conflict badly if I started that work based on `main`.

**Comment by markstos** [comment]
As I've discovered more importing bugs with easy fixes, this PR can be considered still in progress for now if you don't mind a bigger collection of fixes to review later.

I also found  a bug in this PR: I used `@tryghost/errors`, but I didn't didn't add it to `package.json`, and I didn't call it correctly. The happy path doesn't trigger that code path. I can fix that as well.

**Comment by markstos** [comment]
I'm finishing pushing bug fixes to this branch for now. 

I'm currently stuck on a bug where scraping is happening even with `--scrape=none` and  I'm not sure how to fix that ( https://github.com/TryGhost/migrate/issues/515 ).

**Comment by PaulAdamDavis** [comment]
Hey @markstos, thank you so much for your efforts and expertise here, it's massively appreciated! All of this has been merged 🙌

**Pull request merged**
